### ISSUE TITLE
does it only compile once?

### ISSUE THREAD

**Issue by purkylin** [connorslade/advent-of-code#2]
hi, I am a newbee for rust language, will it compile once for the same regex?
If I print the pointer address, it seems different.

```rust
for m in regex!(r"\d+").find_iter(line) {
    let value = m.as_str().parse().unwrap();
```

https://github.com/Basicprogrammer10/advent-of-code/blob/8d4e930217805d36e5e4608c4bd61f349ce8ec34/aoc_2023/src/day_03.rs#L55C1-L56C1

**Comment by purkylin** [comment]
seems macro only expands once in a loop

**Comment by connorslade** [comment]
The macro ([source](https://github.com/Basicprogrammer10/advent-of-code/blob/75c0ad23316e102ea571b3333741246fda0c9f4f/aoc_2023/src/aoc_lib/regex.rs#L2)) expands to the following: 

```rust
{
    static REGEX: once_cell::sync::OnceCell<regex::Regex> = once_cell::sync::OnceCell::new();
    REGEX.get_or_init(|| regex::Regex::new(r"\d+").unwrap())
}
```

This makes use of the [once_cell](http://crates.io/crates/once_cell) crate to only compile the regex once when it is first accessed. (See the [Lazily Compiled Regex](https://docs.rs/once_cell/latest/once_cell/#lazily-compiled-regex) section in the once_cell documentation)

As for printing the pointer, you should see the same address every time.

```rust
for _ in 0..10 {
    let regex = regex!(r"\d+");
    println!("{regex:p}");
}
```

The code snippet above produces the following output.

```
0x7ff77e3831c8
0x7ff77e3831c8
0x7ff77e3831c8
0x7ff77e3831c8
0x7ff77e3831c8
0x7ff77e3831c8
0x7ff77e3831c8
0x7ff77e3831c8
0x7ff77e3831c8
0x7ff77e3831c8
```

Good luck learning Rust!
And with Advent of Code :p
